Logo
Bluespace-community/Bluespace-Station pull request #120
Opened 2023-09-07 19:21 UTC by dopoi16-txt

closes #112
 

 **Описание PR**
  
Добавил лого сервера

 **Медиа** 
  

 **Проверки** 
  
 - [x] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [x] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

 **Изменения** 
 

:cl: dopoi16
- tweak: Изменено лого сервера

2023-09-07 19:33 UTC, Verslebas commented
то что все иконки 256 на 256 так и должно быть?

2023-09-07 19:35 UTC, fedKotikeD commented
Я с телефона смотрю, щас перепроверю. Но по сути нет

2023-09-07 20:39 UTC, fedKotikeD requested changes
1. Все картинки 256х256 формата, исправить
2. Баннер улучшить и сделать красивым, добавить туда аватарку Lizard

2023-09-10 05:37 UTC, fedKotikeD commented
Увы

2023-09-10 05:37 UTC, closed without merging